Exercício 1 Feito
ramonsouzarss/bootcamp-orion-exercicios pull request #4
Opened 2023-10-10 14:09 UTC by ramonsouzarss

2023-10-10 21:15 UTC, aLiviaMs requested changes

2023-10-10 21:15 UTC, aLiviaMs commented on exercicio1/src/exercicio1.ts
> +  const vogais = ["a", "á", "â", "à", "ã", "ä", "å",
Faltou tipar as váriaveis.

2023-10-10 21:15 UTC, aLiviaMs commented on exercicio1/src/exercicio1.ts
> +  const vogais = ["a", "á", "â", "à", "ã", "ä", "å",
Uma **sugestão** de melhoria é utilizar um regex para verificar todas essas variações.
Além de ficar um código mais limpo, são boas práticas na programação, um array para verificar todas as variantes de vogais poderia facilmente ser resumida numa expressão regular.

Desta forma: `vogaisRegex = /[aeiouáàâãéêíóôõúü]/i` só essa linha, somada de um [.match()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match) já diminui a verbosidade do seu código.

Caso queira fazer essa melhoria segue [documentação sobre Expressões regulares (regex)](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Regular_expressions)

2023-10-11 01:37 UTC, ramonsouzarss commented on exercicio1/src/exercicio1.ts
> +  const vogais = ["a", "á", "â", "à", "ã", "ä", "å",
Mudanças realizadas. Muito obrigado pelo feedback!

2023-10-11 01:38 UTC, ramonsouzarss commented on exercicio1/src/exercicio1.ts
> +  const vogais = ["a", "á", "â", "à", "ã", "ä", "å",
Com expressão regular fica muito melhor! Muito obrigado pelo feedback!
Mudanças realizadas.

2023-10-11 13:26 UTC, aLiviaMs requested changes

2023-10-11 13:26 UTC, aLiviaMs commented on exercicio1/src/exercicio1.ts
> +    if (vogaisRegex.includes(palavraMinuscula[i])) {
O método `includes` não é aplicável a objetos do tipo `RegExp`. Para verificar se um caractere corresponde à expressão regular, você deve usar o método `test` da `RegExp`. 

``` 
for (let i = 0; i < palavraMinuscula.length; i++) {
    // Verifica se o caractere é uma vogal.
    if (vogaisRegex.test(palavraMinuscula[i])) {
      // Incrementa a variável de quantidade.
      quantidade++;
    }
  }
```

Informações de qual tipo de método o REGEX aceita estão na documentação do mesmo. Logo no começo da página.
[Expressões Regulares](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Regular_Expressions#:~:text=Express%C3%B5es%20regulares%20s%C3%A3o,regulares%20em%20JavaScript.)

OBS: é importante testar novamente o código e sua funcionalidade antes de subir correções/mudanças de uma PR.

2023-10-11 13:26 UTC, aLiviaMs commented on exercicio1/public/index.html
> +    document.getElementById("contarButton").addEventListener("click", function() {
Deixe o arquivo em ts, dessa funcionalidade tbm, pode ser no arquivo `exercicio1.ts` mesmo

2023-10-12 16:10 UTC, ramonsouzarss commented on exercicio1/src/exercicio1.ts
> +    if (vogaisRegex.includes(palavraMinuscula[i])) {
Alterações feitas
Eu implementei o método test no código html e tinha esquecido de passar para o typescript

2023-10-12 16:11 UTC, ramonsouzarss commented on exercicio1/public/index.html
> +    document.getElementById("contarButton").addEventListener("click", function() {
Alteração feita

2023-10-13 15:16 UTC, aLiviaMs approved these changes

2023-10-13 15:17 UTC, merged